#!/bin/sh

. ../.env

if [ x$NOIPV6 = x1 ]; then
	BINDIP="127.0.0.1"
else
	BINDIP="127.0.0.1,::1"
fi

exec mongod $COMMONDOPTSNOIP \
	--shardsvr \
	--replSet confdb1
	--bind_ip=$BINDIP \
	--port 40001 \
	--ipv6
